- packages/localisation/package-lock.json
- packages/localisation/package.json
- packages/localisation/tsconfig.build.json
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/tsconfig.build.json
- tsconfig.build.json
- Fix TS target version
- Versions bumped
> TS target fixed

- packages/localisation/package-lock.json
- packages/localisation/package.json
- packages/localisation/src/EnDictionary.ts
- packages/localisation/src/StringResources.ts
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/ScheduledEvent/index.ts
- packages/validation/src/index.ts
- tsconfig.build.json
- scheduler localization
- scheduler validation added
> Scheduler related updates

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/ProposalWorkflow/index.ts
This one fixes adding new status to the workflow validation and adds validation for adding next status events inside the workflow.
> SWAP-1118 #validation

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Call/index.ts
- packages/validation/src/User/index.ts
Changes are mainly to fix https://jira.esss.lu.se/browse/SWAP-1176. There was a wrong validation on the `telephone_alt` field which was marked as required but it shouldn't be.
> Swap 1176 user validation improvements

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/ProposalStatuses/index.ts
Changes based on adding new field called `shortCode` into proposal statuses.
> change the proposal status create/update validation

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Call/index.ts
I improved calls create/update validation schemas to align with some database character limitations and split them to be able to do partial validation on the frontend.
> improving and splitting calls validation

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/User/index.ts
User profile validation updated, validation rules existing only on the FE side but missing on the BE added
> SWAP-1246 Use shared validation logic for use profile

- .gitignore
- packages/uows-client-generator/__mocks__/soap.ts
- packages/uows-client-generator/package-lock.json
- packages/uows-client-generator/package.json
- packages/uows-client-generator/src/UOWSServiceClient/UOWSServiceClient.spec.ts
- packages/uows-client-generator/src/index/index.spec.ts
- packages/uows-client-generator/src/index/index.ts
- packages/uows-client-generator/src/test-utils/test-utils.ts
Changes:
-  Tests added for the generated UOWS wrapper functions
- Command line tool now exits with code "1" when it encounters an error
> More test and improvements for UOWS Client Generator

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Instrument/index.ts
Because of the change in the logic and how we submit instrument we need new parameters.
https://jira.esss.lu.se/browse/SWAP-1253
> change submit instrument validation

- packages/uows-client-generator/README.md
- packages/uows-client-generator/package-lock.json
- packages/uows-client-generator/package.json
- packages/uows-client-generator/src/construct-functions/constructFunctions.ts
- packages/uows-client-generator/src/index/index.ts
When using this tool in a command line you can now provide names for the arguments, making it easier to use.
> Added ability to use named arguments when using cl tool.

- packages/logger/src/index.ts
Fix logging on TEST server
Currently, there are no logs for https://useroffice-test.esss.lu.se/ . There should be logs from the test service tagged with the development environment
> Fixing logging for develop

- packages/logger/package.json
> Updating version number

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Admin/index.ts
Validation for creating and updating api access tokens.
> Add api access validation

- packages/logger/package-lock.json
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/SEP/index.ts
Validation ruled fixed for creating new SEP
https://jira.esss.lu.se/browse/SWAP-1343
> SWAP-1343 SEP: mark `numberRatingsRequired` as required

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Proposal/index.ts
- packages/validation/src/Review/index.ts
- packages/validation/src/SEP/index.ts
This PR updates the validation rules for proposal administration, instrument scientist review, and SEP time allocation to disallow negative values (or too large values).
https://jira.esss.lu.se/browse/SWAP-1345
- validation rules updated
> SWAP-1345 Negative values in time allocation should not be allowed

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/SEP/index.ts
This PR updates the params of sep chair/secretary assignment to sep validation.
https://jira.esss.lu.se/browse/SWAP-1340
https://github.com/UserOfficeProject/user-office-frontend/pull/238
https://github.com/UserOfficeProject/user-office-backend/pull/175
> SWAP-1340 SEP Role refactoring

- .eslintrc
- .prettierrc
- package-lock.json
- package.json
- packages/logger/package-lock.json
- packages/logger/package.json
- packages/logger/src/index.ts
- packages/message-broker/package-lock.json
- packages/message-broker/package.json
- packages/message-broker/src/index.ts
- packages/uows-client-generator/__mocks__/soap.ts
- packages/uows-client-generator/src/test-utils/test-utils.ts
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Call/index.ts
- packages/validation/src/Instrument/index.ts
- packages/validation/src/ProposalStatuses/index.ts
- packages/validation/src/ProposalWorkflow/index.ts
- packages/validation/src/Review/index.ts
- packages/validation/src/SEP/index.ts
- packages/validation/src/ScheduledEvent/index.ts
- packages/validation/src/Template/index.ts
- packages/validation/src/User/index.ts
- packages/validation/src/util.ts
Aligning the eslint and prettier versions with useroffice FE and BE and adding better call dates validation.
We need to follow the same code rules and style on all repos and there is need for better call dates validation so end date can not be before start date.
manual, unit and e2e tests.
https://jira.esss.lu.se/browse/SWAP-1372
Fixing eslint/prettier errors/warnings and improving call create/update validation
> Swap 1372 call dates validation

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Proposal/index.ts
New fields added to the proposal administration form and we are updating the validation to include them.
> update proposal administration validation

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/SEP/index.ts
Validation for `saveSepMeetingDecision` and `overwriteSepMeetingDecisionRanking` mutations
> SWAP-1460 validation resolved

- package.json
- packages/logger/package-lock.json
- packages/logger/package.json
- packages/logger/src/index.ts
- packages/message-broker/package-lock.json
- packages/message-broker/package.json
- packages/message-broker/src/index.ts
- logger exception extraction updated, use the same logic in console and graylogger
- replace logError with logException in message broker
> SWAP-1492 Scheduler module should pick up a proposal when it goes into the "scheduled" state

- packages/validation/src/Instrument/index.ts
Add beamline manager validation when creating an instrument
> adding beamline manager validation

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Instrument/index.ts
- packages/validation/src/Proposal/index.ts
- packages/validation/src/Review/index.ts
- packages/validation/src/SEP/index.ts
rename proposalId to proposalPk
> refactor: rename proposalId to proposalPk BREAKING CHANGE

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Proposal/index.ts
fix administrationProposalValidationSchema
> updating administrationProposalValidationSchema

- packages/validation/package.json
- packages/validation/src/Proposal/index.ts
> patch: updating schema

- packages/validation/package.json
- packages/validation/src/Proposal/index.ts
> Update proposal validation schema schema

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/date.ts
When date field wasn't required there was validation error because of the bad logic that we had in the validation.
- e2e tests in the user-office-frontend
> fix some date field issues when it is not required

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/fileUpload.ts
File upload now can be required if we set in the config as required field.
- manual tests
- e2e tests
https://jira.esss.lu.se/browse/SWAP-1676
> Make file upload field required

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Equipment/index.ts
- packages/validation/src/LostTime/index.ts
- packages/validation/src/ProposalBooking/index.ts
- packages/validation/src/ScheduledEvent/index.ts
- packages/validation/src/index.ts
Move Scheduler backend validation to the duo-validation package
> Move scheduler validation to validation package

- packages/localisation/CHANGELOG.md
- packages/localisation/package-lock.json
- packages/localisation/package.json
- packages/logger/CHANGELOG.md
- packages/logger/package-lock.json
- packages/logger/package.json
- packages/logger/src/index.ts
- packages/message-broker/CHANGELOG.md
- packages/message-broker/package-lock.json
- packages/message-broker/package.json
- packages/uows-client-generator/CHANGELOG.md
- packages/uows-client-generator/package-lock.json
- packages/uows-client-generator/package.json
- packages/validation/CHANGELOG.md
- packages/validation/package-lock.json
- packages/validation/package.json
Improve documentaton for logger
* Testing the new package scope
> docs(log): Improve documentation

- package.json
> chore: No verify access token

- packages/validation/src/Questionary/multipleChoice.ts
Adding MultipleChoiceValidation schema
Multiple choice should have same validation rules in frontend and in backend
https://jira.esss.lu.se/browse/SWAP-2112
Added MultipleChoiceValidation schema
> fix(questionary): Adding MultipleChoiceValidation schema 

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/multipleChoice.ts
> Bump version

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/index.ts
- packages/validation/src/Questionary/multipleChoice.ts
> fix: validation does not indicate which question needs

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Call/index.ts
- packages/validation/src/Instrument/index.ts
- packages/validation/src/Questionary/index.ts
- packages/validation/src/Questionary/multipleChoice.ts
- packages/validation/src/Questionary/sampleDeclaration.ts
- packages/validation/src/SEP/index.ts
- packages/validation/src/Template/index.ts
- packages/validation/src/User/index.ts
Add sampleDeclaration validation schema
> fix: Add sampleDeclaration validation schema

- packages/logger/package.json
- packages/logger/src/index.ts
- packages/logger/src/logger.ts
- packages/validation/package.json
- packages/validation/src/Questionary/interval.ts
- packages/validation/src/Questionary/numberInput.ts
> New unit validation

- packages/logger/package-lock.json
- packages/message-broker/package-lock.json
- packages/uows-client-generator/package-lock.json
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Call/index.ts
- packages/validation/src/Instrument/index.ts
- packages/validation/src/Review/index.ts
- packages/validation/src/SEP/index.ts
- packages/validation/src/Template/index.ts
- packages/validation/src/User/index.ts
Increase the character limit on comment from 500 to 1000 characters in proposalGradeValidationSchema.
Currently there is a very small length you can input for comment. Make it longer.
SWAP-2315
Increase the character limit on comment from 500 to 1000 characters in proposalGradeValidationSchema.
> Fix: Increase max comment length to 1000 characters

- packages/validation/src/Questionary/interval.ts
Max must be greater than min
Max must be greater than min
> fix: Max must be greater than min

- packages/uows-client-generator/package-lock.json
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Equipment/index.ts
- packages/validation/src/LostTime/index.ts
- packages/validation/src/Questionary/date.ts
- packages/validation/src/ScheduledEvent/index.ts
This PR is aiming to replace `moment` with `luxon` as we agreed on that to be replaced all around the apps. Also there are some improvements in the date question validation with the message and date normalization when there is time included.
Previously moment was used for date manipulation but now we decided to switch to luxon and this is result of that decision. Also invalid date message was too complex for normal user and we just simplify that. Last but not least is that when time is included validation was very poor and incorrect.
- e2e tests
- manual tests
https://jira.esss.lu.se/browse/SWAP-2345
Backend PR: https://github.com/UserOfficeProject/user-office-frontend/pull/815
Frontend PR: https://github.com/UserOfficeProject/user-office-backend/pull/597
> refactor: replace moment with luxon and improve date validation error message

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Review/index.ts
remove limit, because it is ambiguous, since with Rich Text Input the
length can vary because HTML could be longer or shorter
> fix(reviews): remove limit from YUP

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Review/index.ts
> feat: make status and timeAllocation required on technical review update or submit

- package-lock.json
- package.json
- packages/uows-client-generator/package-lock.json
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/User/index.ts
Improve schema for password confirmation whenever we create user or change/reset some passwords.
- manual tests
- e2e tests on the frontend
https://jira.esss.lu.se/browse/SWAP-2442
Backend PR:
Frontend PR:
> fix(password confirmation): use better validation schema for password confirmation when creating user or reseting passwords

- packages/logger/package-lock.json
- packages/message-broker/package-lock.json
- packages/uows-client-generator/package-lock.json
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/richTextInput.ts
- packages/validation/src/Review/index.ts
- packages/validation/src/util.ts
This is limiting the SEP review comment characters to 2000 and reuses the `sanitizeAndCleanHtml` function for both places where needed.
SEP review comment wasn't limited at all before.
- e2e tests
- manual tests
https://jira.esss.lu.se/browse/SWAP-2494
> feat: Limit SEP review comment characters to 2000

- packages/message-broker/package-lock.json
- packages/message-broker/package.json
- packages/message-broker/src/index.ts
> Swap-2655  Visa setup new queue

- packages/logger/package-lock.json
- packages/message-broker/package-lock.json
- packages/uows-client-generator/package-lock.json
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/PredefinedMessage/index.ts
- packages/validation/src/index.ts
Predefined messages create and update validation schemas
> feat: Add predefined messages validation

- packages/validation/package.json
> release: Increment version number

- packages/openid/package-lock.json
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/date.ts
Update validation for date fields in questions.
Sub templates hang when a user enter an invalid date. 
Files changed: packages/validation/src/Questionary/date.ts
The manually tested with the frontend
> Fix: Update date validation in questions

- packages/message-broker/package-lock.json
- packages/message-broker/package.json
- packages/message-broker/src/index.ts
add sendMessageToExchange method
> feat: add sendMessageToExchange method

- packages/openid/src/OpenIdClient.ts
Add more details to the exception
> fix: add more details to the exception

- packages/logger/package-lock.json
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/dynamicMultipleChoice.ts
Added dynamic multiple choice validation schema
https://jira.esss.lu.se/secure/RapidBoard.jspa?rapidView=798&projectKey=SWAP&view=detail&selectedIssue=SWAP-3047
* manual
packages/validation/src/Questionary/dynamicMultipleChoice.ts
> feat: added dynamic multiple choice validation schema

- packages/message-broker/package-lock.json
- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/index.ts
exported dynamic multi choice validation file
> fix: export dynamic multi choice validation file

- packages/validation/package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/index.ts
- packages/validation/src/Questionary/instrumentPicker.ts
Added YUP validation rule for the new Questionary Component - Instrument Picker
Building new feature to assign an Instrument to a Proposal automatically. To accomplish this, adding a new Questionary Component called Instrument Picker. This Component will be in the form of Radio or Select with the Instrument Lists as options. This PR is to add validation to the Component. 
Manually
> feat: Added new Validation Schema for the InstrumentPicker component.

- package-lock.json
- packages/validation/package.json
- packages/validation/src/ScheduledEvent/index.ts
Improve scheduled event validation
Some test cases are failing because of invalid validation
> fix: fix errors and improve scheduled event validation

- packages/validation/package.json
- packages/validation/src/Call/index.ts
Validation for the Mutation: addSepToCallInstrument
Working on automatic SEP assignment to Proposal upon Instrument selection. To do this, we need to map sep with call and instrument, which needs the call instrument mapping flow to be a little optimized.
> Validation added for the Mutation: updateSepToCallInstrument

- package-lock.json
- packages/validation/package.json
- packages/validation/src/ProposalWorkflow/index.ts
Fix after property name change in the config of email action
> fix: fix the field name as it was changed in the config

- packages/validation/src/util.ts
Closes https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/962
Ref: https://github.com/UserOfficeProject/user-office-core/pull/461
The initial character limt for the FAP review box was 2000, this PR increases it to 6000.
> Increase review box character limit

- packages/validation/package.json
Bum version number for https://github.com/UserOfficeProject/user-office-lib/pull/182 to see changes locally
> bump version number for 962 changes

- packages/validation/package.json
- packages/validation/src/User/index.ts
Remove required fields from updateUser to match what's in the GQL resolver definition. Only ID is required.
> Remove required fields from updateUser

- packages/validation/package.json
- packages/validation/src/User/index.ts
Reverting the change, as it is used in the form
> fix: revert updateUser

- package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/instrumentPicker.ts
This PR aims to fix the instrument picker validation after multi-instrument proposal merge.
There was an issue in the validation for single instrument proposals. 
- e2e tests
- manual tests
> fix(validation): fix instrument picker validation

- package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/index.ts
- packages/validation/src/Questionary/timeRequested.ts
A new question type is added to capture time requested by a user when submitting a proposal.  This PR has the validation for the new question type. This is related to the issue https://github.com/UserOfficeProject/issue-tracker/issues/1044
> fix: validation for new question type TIME_REQUESTED

- package-lock.json
- packages/validation/package.json
- packages/validation/src/Technique/index.ts
To add size restrictions to technique schemas
Part of https://github.com/UserOfficeProject/issue-tracker/issues/1095
> Add size rescrictions to technique schemas

- package-lock.json
- packages/validation/package.json
- packages/validation/src/Technique/index.ts
Description
To change the id field name for update and delete technique schemas
Part of https://github.com/UserOfficeProject/issue-tracker/issues/1095
> Technique id name change

- package-lock.json
- packages/validation/package.json
- packages/validation/src/Technique/index.ts
Description
To allow multiple instruments removal from technique
Part of https://github.com/UserOfficeProject/issue-tracker/issues/1095
> Allow multiple instruments removal from technique

- package-lock.json
- packages/validation/package.json
- packages/validation/src/Technique/index.ts
This add schema for backend validation of assigning and removing scientists from a technique.
Related to https://github.com/UserOfficeProject/user-office-core/pull/652
> add assign scientists to technique schemas

- package-lock.json
- packages/validation/package.json
- packages/validation/src/Questionary/index.ts
- packages/validation/src/Questionary/techniquePicker.ts
Part of https://github.com/UserOfficeProject/issue-tracker/issues/1097
> feat: Add validation for techniquePicker 

- LICENSE
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1166 (user-office-lib)
This is intended for STFC legal and aligns with the Memorandum of Understanding between the contributing parties.
Update licence content
- LICENSE
> feat: update user-office-lib BSD-3 clause licence #1166

- package-lock.json
- packages/validation/package.json
- packages/validation/src/Proposal/index.ts
Part of https://github.com/UserOfficeProject/issue-tracker/issues/1031
> feat: add validation for proposal scientist comment

- packages/validation/package.json
- packages/validation/src/index.ts
> feat: bump validation package version to 5.1.11 and export Invite module

- package-lock.json
- packages/validation/package.json
- packages/validation/src/Statuses/index.ts
- packages/validation/src/Workflow/index.ts
Recently in the User office, the status for experiment and proposal has been uppercased. Updating here as well for validation purpose.
> fix: uppsercasing proposal and experiment statuses

- package-lock.json
- packages/validation/package.json
- packages/validation/src/Call/index.ts
Add experiment parameters including workflow, pdf template in call creation and update. The missing proposal pdf has also been added. 
Add missing parameters to the call creation and update. 
Manual
> feat: add validation for experiment parameters in create and update call
